version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_ENCRYPT=${DB_ENCRYPT}
      - DB_TRUST_CERT=${DB_TRUST_CERT}
      - NODE_ENV=production
    env_file:
      - ./api/.env  # Only for local development
