[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
